services:
 app:
  build: .
  env_file:
   - .env.docker
  ports:
  - "3000:3000"
  volumes:
   - .:/app
   - /app/node_modules

 db:
  image: postgres:17
  env_file:
   - .env.docker
  volumes:
   - postgres_data:/var/lib/postgresql/data
   

 redis: 
  image: redis:8


volumes:
 postgres_data:

